---
version: "3.7"

services:
  db:
    image: postgres:12.2
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=pw
      - POSTGRES_USER=usr
      - POSTGRES_DB=evidapp
    ports:
      - 5432:5432

#  app:
#    build:
#      target: development
#      context: .
#    environment:
#      APP_ENV: dev
#
#    volumes:
#      - .:/usr/src/app/:cached
#    ports:
#      - 3333:3333

volumes:
  db:
