---
version: "3.7"

services:
  db:
    image: postgres:12.2
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=pw
      - POSTGRES_USER=usr
      - POSTGRES_DB=evidapp
    ports:
      - 5432:5432

volumes:
  db:
